### ISSUE TITLE
[Feature Request]: 外部サービスからSkyshareへ入力を送りたい

### ISSUE THREAD

**Issue by tomo-x7** [nekono-dev/skyshare#103]
### Request Details

外部サービスからTwitterとBlueskyの両方にシェアしたいときに、skyshareにシェアすることで、簡単に両方にシェアできるようになる

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる), Make X users better Bluesky, transfer cause (XユーザにBlueskyを魅力的に感じさせ、移行を助長する)

**Comment by nekono-dev** [comment]
説明の内容を考えてタイトルをより全般的にしました！
外部サービスからSkyshareへ、投稿したいテキストやその他データ（画像など）を送れるようになって欲しいという趣旨である認識です。

この課題はへの対応方法は以下に二分できます。優先度は別々に考える必要はありそうですが、いずれも対応できたらできることの幅が広がりそうですね。

## Skyshareに外部データを受け取ることのできるエンドポイントを用意する  
元タイトルの`intent`機能という大枠です。`skyshare.uk/intent&hoge=fuga`といった形でURIパラメータを受け取れるエンドポイントを用意することで解決できます。
これにより、別のサードパーティ製アプリがエンドポイント定義を満たす外部データを、Skyshareの入力としてinput可能になります
一方、クリックジャッキング攻撃などに対して対応する必要があり、入力できるデータについては左記のようなセキュリティの観点から制約を課す必要があります。

## Web Share Target APIに対応する  
モバイル端末などの共有メニューからのデータを受け取れるようにします。エンドポイントよりモバイルフレンドリーであり、できることの幅も広いです。
一方、PCなどのWeb Share機能を持たない端末は恩恵を受けません。

**Comment by nekono-dev** [comment]
v1.4.12にて、`Web Share Target API`の実装（正確には Webアプリマニフェストの`shared_target`メンバ対応）を追加完了しました。（起票ありがとうございました！）
一旦本Issueの実現条件はクリアしたので本Issueはクローズします。
他アプリから操作を行いたい（=エンドポイントとしての実装が欲しい）などの要件/要望があったら、別途Issueとして起こしていただければ幸いです。
