### ISSUE TITLE
[Bug Report]: 一部のウェブサイトで、特定のユーザーエージェントのためにOGP画像が取得できないことがある

### ISSUE THREAD

**Issue by ZEKE320** [nekono-dev/skyshare#110]
### What's the matter?

特定のユーザーエージェントのためにOGPが設定されていないページに遷移し、データが取得できないケースがある。

### When/How the issue was occured?

例）gigazine.net
![image](https://github.com/nkte8/skyshare/assets/46393375/5071adf7-eae4-47a2-8879-13880aa6306a)

### What environmet you using to cause issue?

- OS
  - Windows 11 Home バージョン 23H2
- ブラウザ
  - Microsoft Edge バージョン 124.0.2478.67 (公式ビルド) (64 ビット)

### Can you occur issue again?

1. `http://gigazine.net`のリンクカードを追加する
2. `リンクカード画像を取得できませんでした。`というエラーが表示される。

**Comment by nekono-dev** [comment]
対応ありがとうございました！ @1.4.13にて対応済み
