### ISSUE TITLE
[Feature Request]: Xへの投稿に対してmentionを含むポストのmention→link変換がしたい

### ISSUE THREAD

**Issue by nekono-dev** [nekono-dev/skyshare#23]
### Request Details

SkyshareはBlueskyユーザのメンション(@hoge.bsky.social )に対応しているが、X側ではメンションの形態が異なるため、この識別子は意味を失ってしまう。
X側投稿の際、この識別子をBlueskyのユーザーページへのリンクに置き換えてしまうことで、Blueskyユーザのメンション入りポストをXでも正しく投稿できるようにしたい。

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる), Make X users better Bluesky, transfer cause (XユーザにBlueskyを魅力的に感じさせ、移行を助長する)

**Comment by so-asano** [comment]
@nkte8 
本イシューとは直接関係ないんですが、Bluesky ユーザへのメンションをつかいやすくするためには `app.bsky.actor.searchActorsTypeahead` とかつかってサジェストする必要がありそうですね。

**Comment by nekono-dev** [comment]
入力補助みたいな機能でしょうか、ありがたい。textareaコンポーネントをReactで拡張しているだけの現状、どのように実装するかは別途検討ですが、かなりよさそうです。

**Comment by nekono-dev** [comment]
こちらはねこのが担当します（上記の`searchActorsTypeahead`の実装も考える必要があり、他についても色々調整する必要がありそうなため）

**Comment by nekono-dev** [comment]
入力補助もこれに含めるのはちょっと作業範囲が広すぎるのと、https://github.com/nkte8/skyshare/issues/23#issuecomment-2014353052 を受けたいいアイデアが思いつかなかったため、現在実装できた範囲の部分で本件対応しました。

**Comment by nekono-dev** [comment]
v1.4.7にて対応完了
