### ISSUE TITLE
[Feature Request]: Twitter の文字数カウントの併記

### ISSUE THREAD

**Issue by so-asano** [nekono-dev/skyshare#32]
### Request Details

- twitter の文字数カウントは独特だが、`twitter-text` をつかうとかんたんにできたりもするので、やってもいいのではないかなと

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる)

**Comment by nekono-dev** [comment]
~~#29 に関連~~　←無視してOKです

**Comment by nekono-dev** [comment]
よろしくお願いします② @so-asano

**Comment by so-asano** [comment]
@nkte8 
スマートフォンで 2 種類の文字数を表示する場所がうまくとれなかったので表示がすこしトリッキーなかんじになってます。
このあたりは適宜変更してもらえたらと。

**Comment by nekono-dev** [comment]
v1.4.3にて解消
