### ISSUE TITLE
[Feature Request]: 下書き保存機能

### ISSUE THREAD

**Issue by so-asano** [nekono-dev/skyshare#33]
### Request Details

- たぶんいまは SkyShare に下書き保存機能ってないとおもうんですが、この機能は Bluesky 公式アプリにもなかったりするんで、あったらユーザにとっては便利かもしれない

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる)

**Comment by nekono-dev** [comment]
localstorageを用いた方法(ハッシュタグの候補保存機能の実装と同じ)で対応を考えています。画像情報の保持をデータベースにやらせるのは、流石に無料提供の範囲では厳しいと考えるためです。
(逆にマルチデバイスでの下書き保存対応は有料機能候補)

**Comment by so-asano** [comment]
@nkte8 
これに関連しておもったのですが、書きかけも保存しておいてもいいのかもしれませんね。
アプリのクラッシュや長期間バックグラウンドにあってアプリがキルされる場合など、入力中の下書きが消える場合もあるとおもうので。
（ただ、必要性がどこまであるかはわかりませんが）

**Comment by nekono-dev** [comment]
お任せします🙇 @so-asano

**Comment by so-asano** [comment]
@nkte8 
下書きの画像情報の保存は localStorage だと容量的に厳しそうですね。
ブラウザごとに若干差異があるとはいえ、5 MB とかなので。画像をポスト用に圧縮かけても、たしか画像 1 枚が最大で 1 MB 弱だった気が。
とりあえずは画像の保存は抜きでやってみます。

**Comment by nekono-dev** [comment]
LocalStorageにそんな制限があったとは...いったんは画像抜き了解です。なにかいい方法があればいいのだけれど...

**Comment by so-asano** [comment]
@nkte8 
コミットメッセージのとおり少々雑に実装しました。仕様などについては別途ご説明します。

**Comment by nekono-dev** [comment]
v1.4.3にて解消
