### ISSUE TITLE
[Feature Request]: 画像ファイルのドラッグアンドドロップによる添付機能

### ISSUE THREAD

**Issue by so-asano** [nekono-dev/skyshare#50]
### Request Details

- 入力欄に画像ファイルをドラッグアンドドロップして添付できると PC からのユーザにとっては便利ではないか
- 意外なことに Bluesky の公式ウェブアプリは対応している

### Feature Scope

Usability increase, user satisfication (ユーザビリティ向上させ、利用者を満足させる)

**Comment by so-asano** [comment]
@nkte8 
とりあえずざっと実装はできましたが、デザインとか適当なのでいったんここで止めときます。

**Comment by nekono-dev** [comment]
v1.4.6で対応完了
