### ISSUE TITLE
[Feature Request]: GitHub Actionsによるマージ先ブランチの強制変更

### ISSUE THREAD

**Issue by ZEKE320** [nekono-dev/skyshare#52]
### Request Details

- マージ先ブランチ (base) が`main` `hotfix`である
- マージ元ブランチ (head) が`main` `hotfix` `develop`ではない

という2つの条件が揃っている場合に、マージ先ブランチを強制的に`develop`に変更するGitHub Actionsを導入したい。

### Feature Scope

other, write next (その他。次のフォームに記載する)

### Feature Add infomation

開発環境の改善

**Comment by nekono-dev** [comment]
補足します。hotfixもissueのマージが当てられるべきではないブランチ、役割としてはサイレントアップデートや即席対象の部類のブランチなので、developに変更する対処で良いです！

**Comment by ZEKE320** [comment]
了解です！
- `hotfix` -> `main`
- `develop` -> `main`

のマージを許可しつつ、
- `preview/*` -> `main`
- `preview/*` -> `hotfix`

を防ぐ作りであれば問題ない感じですね

**Comment by nekono-dev** [comment]
↑認識合います！作業実施ありがとうございます🙇

**Comment by nekono-dev** [comment]
@ZEKE320 ぜけさんぜけさん、これってPR出せるブランチ自体の制限とかってできたりします？今回の題目的には関係ないので可能そうだったら、で良いのですが、PR出せるのを`preview`ブランチに絞りたいなあって思ったり…

**Comment by ZEKE320** [comment]
確かに！
少し調べてみますね

**Comment by nekono-dev** [comment]
v1.4.5にて対応済み
