### ISSUE TITLE
[Improve code]: utils/atproto_api/* 手動formatter・Linter対応

### ISSUE THREAD

**Issue by nekono-dev** [nekono-dev/skyshare#62]
### Where and how it seems bad?

utils/atproto_api/* 配下のコードへの対応。
複数人で対応する場合は、作業範囲が被らないようブランチ名に対応ファイルを記載するなどの対応をすること。

- [x] : astro/src/utils/atproto_api/base.ts
- [x] : astro/src/utils/atproto_api/createRecord.ts
- [x] : astro/src/utils/atproto_api/createSession.ts
- [x] : astro/src/utils/atproto_api/deleteSession.ts
- [x] : astro/src/utils/atproto_api/detectFacets.ts
- [x] : astro/src/utils/atproto_api/embeds.ts
- [x] : astro/src/utils/atproto_api/facets.ts
- [x] : astro/src/utils/atproto_api/getPostThread.ts
- [x] : astro/src/utils/atproto_api/getProfile.ts
- [x] : astro/src/utils/atproto_api/getRecord.ts
- [x] : astro/src/utils/atproto_api/getSession.ts
- [x] : astro/src/utils/atproto_api/labels.ts
- [x] : astro/src/utils/atproto_api/record.ts
- [x] : astro/src/utils/atproto_api/refreshSession.ts
- [x] : astro/src/utils/atproto_api/resolveHandle.ts
- [x] : astro/src/utils/atproto_api/uploadBlob.ts

### What it shoud become?

#38 の対応に伴い、フォーマッタ/Linterの対応を実施すること。

**Comment by ZEKE320** [comment]
次の問題について解決する必要があります
- [x] [response.json()がany型扱いとなる問題](https://github.com/nkte8/skyshare/discussions/38#discussioncomment-9027050)
- [x] [namespaceよりES2015 module syntsxが好まれるという警告](https://github.com/nkte8/skyshare/discussions/38#discussioncomment-9027094)
- [x] [union型における"blob"がstringに上書きされている問題](https://github.com/nkte8/skyshare/discussions/38#discussioncomment-9027105)

**Comment by nekono-dev** [comment]
対応完了、ありがとうございました！
