### ISSUE TITLE
[Improve code]: src/utils/*.ts 手動formatter・Linter対応

### ISSUE THREAD

**Issue by nekono-dev** [nekono-dev/skyshare#63]
### Where and how it seems bad?

astro/src/utils/*.ts のコードへの対応。
複数人で対応する場合は、作業範囲が被らないようブランチ名に対応ファイルを記載するなどの対応をすること。

- [x] : astro/src/utils/browserImageCompression.ts
- [x] : astro/src/utils/richTextParser.ts
- [x] : astro/src/utils/useLocalStorage.ts

### What it shoud become?

#38 の対応に伴い、フォーマッタ/Linterの対応を実施すること。

**Comment by ZEKE320** [comment]
次の問題を解決する必要があります。
- [x] [JSON.parse()の戻り値がany型扱いとなる問題](https://github.com/nkte8/skyshare/discussions/38#discussioncomment-9027050)

**Comment by ZEKE320** [comment]
> 次の問題を解決する必要があります。
> 
> - [JSON.parse()の戻り値がany型扱いとなる問題](https://github.com/nkte8/skyshare/discussions/38#discussioncomment-9027050)

以下のPRで仮対応を行いました
- #79

**Comment by nekono-dev** [comment]
対応完了、ありがとうございました！
