### ISSUE TITLE
[Improve code]: VSCodeにおけるESLintのハイライトが正常に表示されない

### ISSUE THREAD

**Issue by nekono-dev** [nekono-dev/skyshare#87]
### Where and how it seems bad?

VSCodeにおいて、正しくコードハイライトが実施されない。これはフォルダへの設定用見込み`vscode/settings.json`の設定が不足しており、VSCodeが正しいルール情報を読み込めていないためである。

### What it shoud become?

VSCodeがフォルダ内の正しい設定値を読み込み、`npx eslint`の実行結果と、VSCodeでのコードハイライトが一致する必要がある。正しい`vscode/settings.json`の作成が必要である。
必要に応じてモノレポもどきを解除し、フロントエンド・バックエンドのリポジトリ分割まで考慮する。

**Comment by nekono-dev** [comment]
~~↑要再確認、単に @nkte8 の節穴だった可能性あり~~

**Comment by nekono-dev** [comment]
起きてる。レビューを実施中の `preview/issue_58`(#84 )について、eslintではエラーが出ないが、VSCode上では`eslint[@typescript-eslint/no-unsafe-return](https://typescript-eslint.io/rules/no-unsafe-return)`が発生している
![image](https://github.com/nkte8/skyshare/assets/91360587/394955b9-9bd5-4579-b309-9f06b2aaebcb)

**Comment by nekono-dev** [comment]
↑以下の設定追加ににより https://github.com/nkte8/skyshare/issues/87#issuecomment-2042572852 のハイライトは解除されたが、逆に出るべき箇所でのエラーが出なくなってしまった。
```
    "eslint.options": {
        "extensions": [".ts", ".tsx", ".jsx", ".astro"],
        "configFile": "astro/.eslintrc.cjs",
    },
```
エラーが出なくなってしまった例: `uploadBlob.ts`
![image](https://github.com/nkte8/skyshare/assets/91360587/e379185b-9a5e-4aa0-a2ec-f6a135a01dea)

**Comment by nekono-dev** [comment]
@ZEKE320 @so-asano 
VScodeの環境設定でESLintの設定を読み込ませる方法について、どのように設定しておりますでしょうか。知見を伺いたいです。
当環境VSCodeの`ESLint`拡張`v2.4.4`をインストールしています。

**Comment by so-asano** [comment]
@nkte8 
基本的には同じような設定だとおもいます（特に Extension の設定をいじってないです）。
上記の件ですが、VS Code で ESLint Server を再起動すると改善したりしませんかね？

**Comment by nekono-dev** [comment]
@so-asano ありがとうございます！
`Control+Shift+P`→`Restart extension host`をやったところ、少なくとも↑↑のファイルに関しては正しく表示されるようになりました、助かりました！

クローズ
